version: 2
jobs:
  build:
    docker:
      - image: predescu/serverless:latest
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
  test:
    docker:
      - image: predescu/serverless:latest
    steps:
      - checkout
      - run:
          name: Testing
          command: echo Testing
  deploy:
    docker:
      - image: predescu/serverless:latest
    steps:
      - checkout
      - run:
          name: Deploy
          command: echo Hello, world.
workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/